spring.application.name=note
spring.datasource.url=jdbc:postgresql://localhost:5432/bacc_db
spring.datasource.username=postgres
spring.datasource.password=ced
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
